apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mlflow-demo
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'mlflow-demo'
    server: '*'
  sourceRepos:
  - '*'