apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-demo-app-of-aps
spec:
  destination:
    namespace: mlflow-demo-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/mlflow-demo/argocd
    repoURL: https://github.com/strangiato/mlflow-demo-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
